package com.example.domain

enum class ErrorSlug {
    PASSWORD_LENGTH_TOO_SHORT,
    PASSWORD_LENGTH_TOO_LONG,
    PASSWORD_MISSING_DIGIT,
    PASSWORD_MISSING_LOWERCASE,
    PASSWORD_MISSING_UPPERCASE,
    PASSWORD_CONTAINS_INVALID_CHARACTERS,
    INVALID_PASSWORD_BIT,
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    INVALID_LOGIN_CREDENTIALS,
    CREATE_USER_CREDENTIALS_INVALID,
    EMAIL_INVALID,
    BALANCE_NOT_SUFFICIENT,
    DEPOSIT_FAILED,
    INVALID_SENDER_CREDENTIALS,
    INVALID_RECIPIENT_CREDENTIALS,
    INVALID_DEPOSIT_CREDENTIALS,
    OPERATION_NEEDS_RECENT_LOGIN
}

class ErrorSlugException(val slug: ErrorSlug): Exception()
